### ISSUE TITLE
Improve ImmutableConciseSet.contains performance

### ISSUE THREAD

**Issue by drcrallen** [metamx/extendedset#8]
https://github.com/metamx/extendedset/pull/6 introduced `ImmutableConciseSet.contains`

Unfortunately, the method used is sub-optimal, as doing a `ImmutableConciseSet.intersection` is faster than the existing `contains`

This ask is to optimize `ImmutableConciseSet.contains` to match or exceed the performance of `ImmutableConciseSet.intersection`

**Comment by drcrallen** [comment]
Suggested benchmark in https://github.com/metamx/extendedset/pull/9

**Comment by drcrallen** [comment]
```
ImmutableConciseSetBenchmark.timeContains: [measured 20 out of 30 rounds, threads: 1 (sequential)]
 round: 1.00 [+- 0.01], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 0, GC.time: 0.00, time.total: 30.04, time.warmup: 10.00, time.bench: 20.04
ImmutableConciseSetBenchmark.timeUnion: [measured 20 out of 30 rounds, threads: 1 (sequential)]
 round: 0.63 [+- 0.01], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 2, GC.time: 0.00, time.total: 19.19, time.warmup: 6.55, time.bench: 12.64
```

**Comment by msj100f** [comment]
Hello,I'm a chinese, thank you for reading this in the busy schedule. I have a question about ConciseSet class, but I can't find the way to contact you. can you help me? 
My question: 
I used ConciseSet in my project,It's no problem for most of the time, but somtimes it's a problem. Exception : 
java.lang.ArrayIndexOutOfBoundsException
        at it.uniroma3.mat.extendedset.rev157.intset.ConciseSet$WordIterator.flush(ConciseSet.java:1003)
        at it.uniroma3.mat.extendedset.rev157.intset.ConciseSet$WordIterator.access$1000(ConciseSet.java:889)
        at it.uniroma3.mat.extendedset.rev157.intset.ConciseSet.performOperation(ConciseSet.java:1102)
        at it.uniroma3.mat.extendedset.rev157.intset.ConciseSet.add(ConciseSet.java:1974)

Can you help me? Thank you!

**Comment by msj100f** [comment]
I'm so sorry forget tell you my email(msj100f@163.com).
